class_name CharacterDesigns
extends RefCounted
## Hand-drawn 16x16 overworld characters, built from interchangeable parts.
##
## A character is a head (rows 0-9; long hair or beards may spill lower) drawn
## over a body (rows 10-15). PixelArt.CHARACTERS picks the parts and colors
## for each person, and PixelArt.character_sheet() turns them into a walking
## sheet. Walking frames reuse rows 1-12 of the standing frame (a 1px bob) and
## add the body's leg poses. Right-facing frames are mirrored from "side".
##
## Letters are colors from the character's palette; "." is transparent.
## Shared by every character: K outline, S/s skin, E eyes, W white.
## Per character: H/h hair or hat, A/a accent (cap logo, ribbons, bandana),
## R/r hair under a hat, G/L glasses frame/lens, B/b top, C/c coat or apron,
## P pants or skirt, F shoes, X/x backpack.

const HEADS := {
	&"cap": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHAAHHHK...",
			"...KHHHHHHHHK...",
			"..KhhhhhhhhhhK..",
			"...KRSSSSSSRK...",
			"...KSESSSSESK...",
			"...KSSSSSSSSK...",
			"....KKsSSsKK....",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			"...KHHHHHHHHK...",
			"..KhhhhhhhhhhK..",
			"...KRRRRRRRRK...",
			"...KRRRRRRRRK...",
			"...KrRRRRRRrK...",
			"....KKSSSSKK....",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KHHHHHK....",
			"....KHHHHAHHK...",
			"....KHHHHHHHK...",
			".KKhhhhhhhhhK...",
			"....KSSSSRRRK...",
			"....KESSSRRRK...",
			"....KSSSSSRK....",
			".....KsSSKK.....",
		],
	},
	&"prof": {
		"front": [
			"................",
			"....KK.KK.KK....",
			"...KHHKHHKHHK...",
			"..KHHHHHHHHHHK..",
			"..KHhHHHHHHhHK..",
			"..KhhhhhhhhhhK..",
			"...KhSSSSSShK...",
			"...KGLGSSGLGK...",
			"...KSSSSSSSSK...",
			"....KKsSSsKK....",
		],
		"back": [
			"................",
			"....KK.KK.KK....",
			"...KHHKHHKHHK...",
			"..KHHHHHHHHHHK..",
			"..KHHHHHHHHHHK..",
			"..KHhHHHHHHhHK..",
			"...KhHHHHHHhK...",
			"...KhhhhhhhhK...",
			"...KSShhhhSSK...",
			"....KKSSSSKK....",
		],
		"side": [
			"................",
			".....KK.KK.K....",
			"....KHHKHHKHK...",
			"...KHHHHHHHHHK..",
			"...KHHHHHHHhHK..",
			"...KhhhhHHhhHK..",
			"...KSSSShhhhK...",
			"..KLGSSSShhK....",
			"...KSSSSSShK....",
			"....KKsSSKK.....",
		],
	},
	&"long": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			"..KHHhHHHHhHHK..",
			"..KHhSSSSSShHK..",
			"..KHKSSSSSSKHK..",
			"..KHSESSSSESHK..",
			"..KHSSSSSSSSHK..",
			"..KhKKsSSsKKhK..",
			"..KhK......KhK..",
			"..KK........KK..",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			"..KHHHHhhHHHHK..",
			"..KHHHHhhHHHHK..",
			"..KHHHHHHHHHHK..",
			"..KHhHHHHHHhHK..",
			"..KHhHHHHHHhHK..",
			"..KhHHHHHHHHhK..",
			"..KhhHHHHHHhhK..",
			"...KKhhhhhhKK...",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KHHHHHK....",
			"....KHHHHHHHK...",
			"...KHHHHHHHHHK..",
			"...KHSSSHHHHHK..",
			"....KSSSShHHHK..",
			"....KESSSShHHK..",
			"....KSSSSShHHK..",
			".....KsSSKhHhK..",
			"........KhHhK...",
			"........KKKK....",
		],
	},
	&"pigtails": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			".KKKHhHHHHhHKKK.",
			"KAAKhSSSSSShKAAK",
			".KHHKSSSSSSKHHK.",
			".KHKSESSSSESKHK.",
			".KhKSSSSSSSSKhK.",
			"..K.KKsSSsKK.K..",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			".KKKHHHHHHHHKKK.",
			"KAAKHHHHHHHHKAAK",
			".KHHKHHHHHHKHHK.",
			".KHKHHHHHHHHKHK.",
			".KhKhHHHHHHhKhK.",
			"..K.KKSSSSKK.K..",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KHHHHHK....",
			"....KHHHHHHHK...",
			"....KHHHHHHHKKK.",
			"...KHSSSHHHKAAK.",
			"....KSSSShHKHHK.",
			"....KESSSShKHK..",
			"....KSSSSShKhK..",
			".....KsSSKK.K...",
		],
	},
	&"elder": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KSSSSSSK....",
			"...KSSSSWSSSK...",
			"...KSSSSSSSSK...",
			"..KHSSSSSSSSHK..",
			"..KHKSSSSSSKHK..",
			"...KSESSSSESK...",
			"...KSHHHHHHSK...",
			"....KHHHHHHK....",
			"....KhHHHHhK....",
			".....KhhhhK.....",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KSSSSSSK....",
			"...KSSSSSSSSK...",
			"...KSSSSSSSSK...",
			"..KHSSSSSSSSHK..",
			"..KHHSSSSSSHHK..",
			"...KHHHHHHHHK...",
			"...KhHHHHHHhK...",
			"....KKSSSSKK....",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KSSSSSK....",
			"....KSSSSWSSK...",
			"....KSSSSSSSK...",
			"....KSSSSSHHK...",
			"....KSSSSHHHK...",
			"....KESSSHHHK...",
			"...KHHHSSSHK....",
			"....KHHHHKK.....",
			"....KhHHK.......",
			".....KKK........",
		],
	},
	&"bandana": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KAAAAAAK....",
			"...KAAaAAaAAK...",
			"...KAAAAAAAAK...",
			"..KaaaaaaaaaaK..",
			"...KHSSSSSSHK...",
			"...KSESSSSESK...",
			"...KHSSSSSSHK...",
			"....KHHHHHHK....",
			"....KhHHHHhK....",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KAAAAAAK....",
			"...KAAAAAAAAK...",
			"...KAAAAAAAAK...",
			"..KaaaaKKaaaaK..",
			"...KHHKaaKHHK...",
			"...KHHHKKHHHK...",
			"...KhHHHHHHhK...",
			"....KKSSSSKK....",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KAAAAAK....",
			"....KAAAAaAAK...",
			"....KAAAAAAAK...",
			"...KaaaaaaaaaK..",
			"....KSSSSHHHKaK.",
			"....KESSSHHHKK..",
			"...KHHSSSSHK....",
			"....KHHHHHK.....",
			".....KhHhK......",
		],
	},
	&"swimcap": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			"...KGLGHHGLGK...",
			"...KhhhhhhhhK...",
			"...KSSSSSSSSK...",
			"...KSESSSSESK...",
			"...KSSSSSSSSK...",
			"....KKsSSsKK....",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KHHHHHHK....",
			"...KHHHHHHHHK...",
			"...KGGGGGGGGK...",
			"...KhhhhhhhhK...",
			"...KSSSSSSSSK...",
			"...KSSSSSSSSK...",
			"...KsSSSSSSsK...",
			"....KKSSSSKK....",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KHHHHHK....",
			"....KHHHHHHHK...",
			"...KLGGGGGGGK...",
			"....KhhhhhhhK...",
			"....KSSSSSSSK...",
			"....KESSSSSSK...",
			"....KSSSSSSK....",
			".....KsSSKK.....",
		],
	},
	&"spiky": {
		"front": [
			"................",
			"...K...KK...K...",
			"..KHK.KHHK.KHK..",
			"..KHHKHHHHKHHK..",
			"..KHHHHHHHHHHK..",
			"..KHhHHHHHHhHK..",
			"...KhSSSSSShK...",
			"...KSESSSSESK...",
			"...KSSSSSSSSK...",
			"....KKsSSsKK....",
		],
		"back": [
			"................",
			"...K...KK...K...",
			"..KHK.KHHK.KHK..",
			"..KHHKHHHHKHHK..",
			"..KHHHHHHHHHHK..",
			"..KHHHHHHHHHHK..",
			"...KHhHHHHhHK...",
			"...KhHHHHHHhK...",
			"...KShhhhhhSK...",
			"....KKSSSSKK....",
		],
		"side": [
			"................",
			".....K..K.......",
			"....KHKKHK.K....",
			"...KHHHHHHKHK...",
			"...KHHHHHHHHHK..",
			"...KhHHHHHHhHK..",
			"....KSSSShHHHK..",
			"....KESSSShHK...",
			"....KSSSSShK....",
			".....KsSSKK.....",
		],
	},
	&"nurse": {
		"front": [
			"................",
			".....KKKKKK.....",
			"....KWWWWWWK....",
			"...KWWWAAWWWK...",
			"...KHHHHHHHHK...",
			"..KHHhHHHHhHHK..",
			"..KHhSSSSSShHK..",
			"..KHSESSSSESHK..",
			"..KHSSSSSSSSHK..",
			"..KhKKsSSsKKhK..",
			"..KK........KK..",
		],
		"back": [
			"................",
			".....KKKKKK.....",
			"....KWWWWWWK....",
			"...KWWWWWWWWK...",
			"...KHHHHHHHHK...",
			"..KHHHHKKHHHHK..",
			"..KHHHKHHKHHHK..",
			"..KHHHKHhKHHHK..",
			"..KHhHHKKHHhHK..",
			"..KhHHHHHHHHhK..",
			"..KK........KK..",
		],
		"side": [
			"................",
			"......KKKKK.....",
			".....KWWWWWK....",
			"....KWWWWAWWK...",
			"....KHHHHHHHK...",
			"...KHHHHHHHHHK..",
			"....KSSSShHHHK..",
			"....KESSSShHHK..",
			"....KSSSSShHHK..",
			".....KsSSKhHhK..",
			"........KKKK....",
		],
	},
}

## Bodies list front/side rows (and back, when it differs from front) plus
## two leg poses each for walking toward/away from the camera and sideways.
const BODIES := {
	&"tee": {
		"front": [
			"...KBBBBBBBBK...",
			"..KSKBBBBBBKSK..",
			"..KsKbBBBBbKsK..",
			"...KKPPPPPPKK...",
			"....KPPKKPPK....",
			"...KFFK..KFFK...",
		],
		"side": [
			"....KBBBBBBK....",
			"....KBBSBBBK....",
			"....KbBSBBbK....",
			".....KPPPPK.....",
			".....KPPPPK.....",
			"....KFFFFK......",
		],
		"walk_front": [
			["....KPPPPPPK....", "....KPPKKPPK....", "....KPPK.KFFK...", "...KFFK........."],
			["....KPPPPPPK....", "....KPPKKPPK....", "...KFFK.KPPK....", ".........KFFK..."],
		],
		"walk_side": [
			[".....KPPPPK.....", "....KPPKKPPK....", "...KPPK..KPPK...", "..KFFK....KFFK.."],
			[".....KPPPPK.....", ".....KPPPPK.....", "......KPPK......", ".....KFFFK......"],
		],
	},
	&"pack": {
		"front": [
			"...KBXBBBBXBK...",
			"..KSKXBBBBXKSK..",
			"..KsKbBBBBbKsK..",
			"...KKPPPPPPKK...",
			"....KPPKKPPK....",
			"...KFFK..KFFK...",
		],
		"back": [
			"...KXXXXXXXXK...",
			"..KSKXxXXxXKSK..",
			"..KsKXXXXXXKsK..",
			"...KKxxxxxxKK...",
			"....KPPKKPPK....",
			"...KFFK..KFFK...",
		],
		"side": [
			"....KBBBBBKXXK..",
			"....KBBSBBKXXK..",
			"....KbBSBBKxXK..",
			".....KPPPPKKK...",
			".....KPPPPK.....",
			"....KFFFFK......",
		],
		"walk_front": [
			["....KPPPPPPK....", "....KPPKKPPK....", "....KPPK.KFFK...", "...KFFK........."],
			["....KPPPPPPK....", "....KPPKKPPK....", "...KFFK.KPPK....", ".........KFFK..."],
		],
		"walk_side": [
			[".....KPPPPK.....", "....KPPKKPPK....", "...KPPK..KPPK...", "..KFFK....KFFK.."],
			[".....KPPPPK.....", ".....KPPPPK.....", "......KPPK......", ".....KFFFK......"],
		],
	},
	&"jacket": {
		"front": [
			"...KBBCCCCBBK...",
			"..KSKBBCCBBKSK..",
			"..KsKbBCCBbKsK..",
			"...KKPPPPPPKK...",
			"....KPPKKPPK....",
			"...KFFK..KFFK...",
		],
		"back": [
			"...KBBBBBBBBK...",
			"..KSKBBBBBBKSK..",
			"..KsKbBBBBbKsK..",
			"...KKPPPPPPKK...",
			"....KPPKKPPK....",
			"...KFFK..KFFK...",
		],
		"side": [
			"....KCBBBBBK....",
			"....KCBSBBBK....",
			"....KbBSBBbK....",
			".....KPPPPK.....",
			".....KPPPPK.....",
			"....KFFFFK......",
		],
		"walk_front": [
			["....KPPPPPPK....", "....KPPKKPPK....", "....KPPK.KFFK...", "...KFFK........."],
			["....KPPPPPPK....", "....KPPKKPPK....", "...KFFK.KPPK....", ".........KFFK..."],
		],
		"walk_side": [
			[".....KPPPPK.....", "....KPPKKPPK....", "...KPPK..KPPK...", "..KFFK....KFFK.."],
			[".....KPPPPK.....", ".....KPPPPK.....", "......KPPK......", ".....KFFFK......"],
		],
	},
	&"coat": {
		"front": [
			"..KCCKBBBBKCCK..",
			".KSKCCBBBBCCKSK.",
			".KsKCcBBBBcCKsK.",
			"..KCCcPPPPcCCK..",
			"...KKKPKKPKKK...",
			"...KFFK..KFFK...",
		],
		"back": [
			"..KCCCCCCCCCCK..",
			".KSKCCCCCCCCKSK.",
			".KsKCCCcCCCCKsK.",
			"..KCCCCcCCCCCK..",
			"...KKKPKKPKKK...",
			"...KFFK..KFFK...",
		],
		"side": [
			"....KCCCCCCK....",
			"...KCCBSCCCK....",
			"...KCCBSCCcK....",
			"...KCCPPPPcK....",
			".....KPPPPK.....",
			"....KFFFFK......",
		],
		"walk_front": [
			["..KCCcPPPPcCCK..", "...KKKPKKPKKK...", "....KPPK.KFFK...", "...KFFK........."],
			["..KCCcPPPPcCCK..", "...KKKPKKPKKK...", "...KFFK.KPPK....", ".........KFFK..."],
		],
		"walk_side": [
			["...KCCPPPPcK....", "....KPPKKPPK....", "...KPPK..KPPK...", "..KFFK....KFFK.."],
			["...KCCPPPPcK....", ".....KPPPPK.....", "......KPPK......", ".....KFFFK......"],
		],
	},
	&"dress": {
		"front": [
			"...KBBBBBBBBK...",
			"..KSKBBBBBBKSK..",
			"..KsKbBBBBbKsK..",
			"..KPPPPPPPPPPK..",
			"..KKKKKKKKKKKK..",
			"....KFK..KFK....",
		],
		"side": [
			"....KBBBBBBK....",
			"....KBBSBBBK....",
			"....KbBSBBbK....",
			"...KPPPPPPPPK...",
			"...KKKKKKKKKK...",
			".....KFFFK......",
		],
		"walk_front": [
			["..KPPPPPPPPPPK..", "..KKKKKKKKKKKK..", "....KSK..KFK....", "....KFK........."],
			["..KPPPPPPPPPPK..", "..KKKKKKKKKKKK..", "....KFK..KSK....", ".........KFK...."],
		],
		"walk_side": [
			["...KPPPPPPPPK...", "...KKKKKKKKKK...", "....KSK..KSK....", "...KFK....KFK..."],
			["...KPPPPPPPPK...", "...KKKKKKKKKK...", ".....KSKSK......", ".....KFFFK......"],
		],
	},
	&"apron": {
		"front": [
			"...KBCCCCCCBK...",
			"..KSKCCCCCCKSK..",
			"..KsKCcCCcCKsK..",
			"..KPPCCCCCCPPK..",
			"..KKKKKKKKKKKK..",
			"....KFK..KFK....",
		],
		"back": [
			"...KBBBBBBBBK...",
			"..KSKBBCCBBKSK..",
			"..KsKbCBBCbKsK..",
			"..KPPPPPPPPPPK..",
			"..KKKKKKKKKKKK..",
			"....KFK..KFK....",
		],
		"side": [
			"....KCBBBBBK....",
			"....KCBSBBBK....",
			"....KCBSBBbK....",
			"...KCCPPPPPPK...",
			"...KKKKKKKKKK...",
			".....KFFFK......",
		],
		"walk_front": [
			["..KPPCCCCCCPPK..", "..KKKKKKKKKKKK..", "....KSK..KFK....", "....KFK........."],
			["..KPPCCCCCCPPK..", "..KKKKKKKKKKKK..", "....KFK..KSK....", ".........KFK...."],
		],
		"walk_side": [
			["...KCCPPPPPPK...", "...KKKKKKKKKK...", "....KSK..KSK....", "...KFK....KFK..."],
			["...KCCPPPPPPK...", "...KKKKKKKKKK...", ".....KSKSK......", ".....KFFFK......"],
		],
	},
	&"robe": {
		"front": [
			"...KBBBBBBBBK...",
			"..KSKBBbbBBKSK..",
			"..KsKBBbbBBKsK..",
			"...KBBBbbBBBK...",
			"...KBBBbbBBBK...",
			"...KKFFKKFFKK...",
		],
		"side": [
			"....KBBBBBBK....",
			"....KBBSBBBK....",
			"....KbBSBBbK....",
			"....KBBBBBBK....",
			"...KBBBBBBBBK...",
			"...KFFKKKKKKK...",
		],
		"walk_front": [
			["...KBBBbbBBBK...", "...KBBBbbBBBK...", "...KBBBbbBBBK...", "...KFFKKKKKKK..."],
			["...KBBBbbBBBK...", "...KBBBbbBBBK...", "...KBBBbbBBBK...", "...KKKKKKKFFK..."],
		],
		"walk_side": [
			["....KBBBBBBK....", "....KBBBBBBK....", "...KBBBBBBBBK...", "..KFFKKKKKKKK..."],
			["....KBBBBBBK....", "....KBBBBBBK....", "...KBBBBBBBBK...", "...KKKKKKKFFK..."],
		],
	},
	&"swim": {
		"front": [
			"...KSBBBBBBSK...",
			"..KSKBBBBBBKSK..",
			"..KsKBBBBBBKsK..",
			"...KKBBBBBBKK...",
			"....KSSKKSSK....",
			"....KSK..KSK....",
		],
		"side": [
			"....KSBBBBSK....",
			"....KBBSBBBK....",
			"....KBBSBBBK....",
			".....KBBBBK.....",
			".....KSSSSK.....",
			".....KSSSK......",
		],
		"walk_front": [
			["....KBBBBBBK....", "....KSSKKSSK....", "....KSSK.KSK....", "....KSK........."],
			["....KBBBBBBK....", "....KSSKKSSK....", "....KSK.KSSK....", ".........KSK...."],
		],
		"walk_side": [
			[".....KBBBBK.....", "....KSSKKSSK....", "...KSSK..KSSK...", "...KSK....KSK..."],
			[".....KBBBBK.....", ".....KSSSSK.....", "......KSSK......", ".....KSSSK......"],
		],
	},
}
