class_name EffectDesigns
extends RefCounted
## Hand-drawn battle effect sprites (MoveAnimator draws them at 2x, like the
## monsters). Letters are colors from the effect's entry in PixelArt.EFFECTS;
## "." is transparent. Effects listed in OUTLINED get a 1px ink outline so
## they read against both the sky and the monsters.

const OUTLINED: Array[StringName] = [&"flame", &"drop", &"leaf", &"rock", &"spark", &"shadow", &"arrow_up", &"arrow_down", &"impact"]

const EFFECTS := {
	&"flame": [
		"..........",
		"....R.....",
		"...RR.....",
		"...ROR..R.",
		"..ROORRRR.",
		"..ROYYOOR.",
		".ROYWWYOR.",
		".ROYWWYOR.",
		"..ROYYOR..",
		"...RRRR...",
	],
	&"drop": [
		"..........",
		"....L.....",
		"....L.....",
		"...LBB....",
		"...LBBB...",
		"..LWBBBb..",
		"..LWBBBb..",
		"..BBBBbb..",
		"...bbbb...",
		"..........",
	],
	&"bubble": [
		"..........",
		"...BBBB...",
		"..BWW..B..",
		".BW.....B.",
		".BW.....B.",
		".B......B.",
		".B.....bB.",
		"..B...bB..",
		"...BBBB...",
		"..........",
	],
	&"leaf": [
		"..........",
		"......GG..",
		"....GGLG..",
		"...GLLGG..",
		"..GLLGGg..",
		"..GLGGg...",
		"..GGgg....",
		".gg.......",
		"..........",
		"..........",
	],
	&"rock": [
		"..........",
		"..........",
		"...RRRR...",
		"..RLLRRR..",
		".RLRRRRrR.",
		".RRRRRrrR.",
		".RRRRrrrr.",
		"..rrrrrr..",
		"..........",
		"..........",
	],
	&"spark": [
		"....W....",
		"....Y....",
		".Y..Y..Y.",
		"..Y.W.Y..",
		"...WWW...",
		"WYWWWWWYW",
		"...WWW...",
		"..Y.W.Y..",
		".Y..Y..Y.",
	],
	&"shadow": [
		"..........",
		"...PPPP...",
		"..PMMPPP..",
		".PMMPPPnP.",
		".PMPPPPnP.",
		".PPPPPnnP.",
		".PPPPnnnP.",
		"..PnnnnP..",
		"...PPPP...",
		"..........",
	],
	&"glint": [
		"...W...",
		"...Y...",
		"..YWY..",
		"WYWWWYW",
		"..YWY..",
		"...Y...",
		"...W...",
	],
	&"arrow_up": [
		".........",
		"....A....",
		"...AAA...",
		"..AAAAA..",
		".AAAAAAA.",
		"...AAA...",
		"...AAA...",
		"...aaa...",
		".........",
	],
	&"arrow_down": [
		".........",
		"...aaa...",
		"...AAA...",
		"...AAA...",
		".AAAAAAA.",
		"..AAAAA..",
		"...AAA...",
		"....A....",
		".........",
	],
	&"impact": [
		"...............",
		".......W.......",
		".W.....W.....W.",
		"..W...WYW...W..",
		"...W..WYW..W...",
		"....WWYYYWW....",
		"...WYYYWYYYW...",
		".WWYYYWWWYYYWW.",
		"...WYYYWYYYW...",
		"....WWYYYWW....",
		"...W..WYW..W...",
		"..W...WYW...W..",
		".W.....W.....W.",
		".......W.......",
		"...............",
	],
	&"slash": [
		"................",
		"..........W..W.W",
		".........W..W.W.",
		"........W..W.W..",
		".......W..W.W...",
		"......W..W.W....",
		".....W..W.W.....",
		"....W..W.W......",
		"...W..W.W.......",
		"..W..W.W........",
		".W..W.W.........",
		"W..W.W..........",
		"...W............",
		"................",
		"................",
		"................",
	],
}
